services:

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: catalisa
      POSTGRES_PASSWORD: catalisa123
      POSTGRES_DB: catalisa_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://catalisa:catalisa123@db:5432/catalisa_db
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data: