"""create tables

Revision ID: fc6f2aab57df
Revises: 
Create Date: 2026-05-23 22:26:52.037306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc6f2aab57df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This revision is intentionally retained as the baseline revision
    # for later migrations that depend on it.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Symmetric explicit no-op for the baseline revision.
    pass
    # ### end Alembic commands ###